#!/bin/sh
#
# Hook script to verify changes about to be committed.
# The hook should exit with non-zero status after issuing an appropriate
# message if it wants to stop the commit.

git diff --cached --diff-filter=ACM --quiet xml/*.xml

# get status
status=$?

if [ $status -ne 0 ]; then
    # Verify that each fingerprint asserts known identifiers.
    ./bin/recog_standardize --write xml/*.xml
    # get status
    status=$?

    if [ $status -ne 0 ]; then
        echo "Please review any new additions to the text files under 'identifiers/'."
        echo "If any of these names are close to an existing name, update the offending"
        echo "fingerprint to use the existing name instead. Once the fingerprints are fixed"
        echo "run the 'bin/recog_standardize' tool again."
        exit 1
    fi
fi

exit 0